// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly:AssemblyTitleAttribute("FAKE - F# Make Integration into GitHub Actions buildserver")>][<assembly:AssemblyProductAttribute("FAKE - F# Make")>][<assembly:AssemblyVersionAttribute("5.19.1")>][<assembly:AssemblyInformationalVersionAttribute("5.19.1")>][<assembly:AssemblyFileVersionAttribute("5.19.1")>][<assembly:AssemblyMetadataAttribute("BuildDate",
                                                                                                                                                                                                                                                                                                                                                           "2020-05-04")>]

do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle =
        "FAKE - F# Make Integration into GitHub Actions buildserver"

    [<Literal>]
    let AssemblyProduct = "FAKE - F# Make"

    [<Literal>]
    let AssemblyVersion = "5.19.1"

    [<Literal>]
    let AssemblyInformationalVersion = "5.19.1"

    [<Literal>]
    let AssemblyFileVersion = "5.19.1"

    [<Literal>]
    let AssemblyMetadata_BuildDate = "2020-05-04"
