// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make SSH operations")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.21.1")>]
[<assembly: AssemblyInformationalVersionAttribute("5.21.1")>]
[<assembly: AssemblyFileVersionAttribute("5.21.1")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2022-01-31")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make SSH operations"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.21.1"
    let [<Literal>] AssemblyInformationalVersion = "5.21.1"
    let [<Literal>] AssemblyFileVersion = "5.21.1"
    let [<Literal>] AssemblyMetadata_BuildDate = "2022-01-31"
