// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Octopus Deploy octo.exe tool helper")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.3.1")>]
[<assembly: AssemblyInformationalVersionAttribute("5.3.1-alpha")>]
[<assembly: AssemblyFileVersionAttribute("5.3.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Octopus Deploy octo.exe tool helper"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.3.1"
    let [<Literal>] AssemblyInformationalVersion = "5.3.1-alpha"
    let [<Literal>] AssemblyFileVersion = "5.3.1"
