
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

module Fake.AssemblyInfo
#nowarn "49" // uppercase argument names
#nowarn "67" // this type test or downcast will always hold
#nowarn "66" // this upcast is unnecessary - the types are identical
#nowarn "58" // possible incorrect indentation..
#nowarn "57" // do not use create_DelegateEvent
#nowarn "51" // address-of operator can occur in the code
open System
open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices

exception ReturnExceptioneac098dbc86e49f6b011a9091d81b9f8 of obj
exception ReturnNoneExceptioneac098dbc86e49f6b011a9091d81b9f8

[<assembly: ComVisible (false)>]
[<assembly: CLSCompliant (false)>]
[<assembly: Guid ("fb2b540f-d97a-4660-972f-5eeff8120fba")>]
[<assembly: AssemblyTitle ("FAKE - F# Make Command line tool")>]
[<assembly: AssemblyProduct ("FAKE - F# Make Command line tool")>]
[<assembly: AssemblyVersion ("0.2")>]
[<assembly: AssemblyFileVersion ("0.2")>]
[<assembly: AssemblyDelaySign (false)>]
()
