// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Experimental Lib")>]
[<assembly: GuidAttribute("5AA28AED-B9D8-4158-A594-32FE5ABC5713")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.13.1")>]
[<assembly: AssemblyInformationalVersionAttribute("5.13.1")>]
[<assembly: AssemblyFileVersionAttribute("5.13.1")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2019-04-22")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Experimental Lib"
    let [<Literal>] Guid = "5AA28AED-B9D8-4158-A594-32FE5ABC5713"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.13.1"
    let [<Literal>] AssemblyInformationalVersion = "5.13.1"
    let [<Literal>] AssemblyFileVersion = "5.13.1"
    let [<Literal>] AssemblyMetadata_BuildDate = "2019-04-22"
