// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FAKE - F# Make SQL Lib")>]
[<assembly: GuidAttribute("A161EAAF-EFDA-4EF2-BD5A-4AD97439F1BE")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("4.61.2")>]
[<assembly: AssemblyInformationalVersionAttribute("4.61.2")>]
[<assembly: AssemblyFileVersionAttribute("4.61.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make SQL Lib"
    let [<Literal>] Guid = "A161EAAF-EFDA-4EF2-BD5A-4AD97439F1BE"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "4.61.2"
    let [<Literal>] AssemblyInformationalVersion = "4.61.2"
    let [<Literal>] AssemblyFileVersion = "4.61.2"
