// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Sql Server operations")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.7.3")>]
[<assembly: AssemblyInformationalVersionAttribute("5.7.3-alpha")>]
[<assembly: AssemblyFileVersionAttribute("5.7.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Sql Server operations"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.7.3"
    let [<Literal>] AssemblyInformationalVersion = "5.7.3-alpha"
    let [<Literal>] AssemblyFileVersion = "5.7.3"
