// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Lib")>]
[<assembly: InternalsVisibleToAttribute("Test.FAKECore")>]
[<assembly: GuidAttribute("d6dd5aec-636d-4354-88d6-d66e094dadb5")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.13.1")>]
[<assembly: AssemblyInformationalVersionAttribute("5.13.1")>]
[<assembly: AssemblyFileVersionAttribute("5.13.1")>]
[<assembly: AssemblyMetadataAttribute("BuildDate", "2019-04-22")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "FAKE - F# Make Lib"

    [<Literal>]
    let InternalsVisibleTo = "Test.FAKECore"

    [<Literal>]
    let Guid = "d6dd5aec-636d-4354-88d6-d66e094dadb5"

    [<Literal>]
    let AssemblyProduct = "FAKE - F# Make"

    [<Literal>]
    let AssemblyVersion = "5.13.1"

    [<Literal>]
    let AssemblyInformationalVersion = "5.13.1"

    [<Literal>]
    let AssemblyFileVersion = "5.13.1"

    [<Literal>]
    let AssemblyMetadata_BuildDate = "2019-04-22"
