// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make User input helpers")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.1")>]
[<assembly: AssemblyInformationalVersionAttribute("5.1.0-alpha.1")>]
[<assembly: AssemblyFileVersionAttribute("5.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make User input helpers"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.1"
    let [<Literal>] AssemblyInformationalVersion = "5.1.0-alpha.1"
    let [<Literal>] AssemblyFileVersion = "5.1.0"
