// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make FTP operations")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.22.0")>]
[<assembly: AssemblyInformationalVersionAttribute("5.22.0-alpha001.local.3+2022-02-07-14-27")>]
[<assembly: AssemblyFileVersionAttribute("5.22.0")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2022-02-07")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make FTP operations"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.22.0"
    let [<Literal>] AssemblyInformationalVersion = "5.22.0-alpha001.local.3+2022-02-07-14-27"
    let [<Literal>] AssemblyFileVersion = "5.22.0"
    let [<Literal>] AssemblyMetadata_BuildDate = "2022-02-07"
