// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Deploy tool")>]
[<assembly: GuidAttribute("413E2050-BECC-4FA6-87AA-5A74ACE9B8E1")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.13.1")>]
[<assembly: AssemblyInformationalVersionAttribute("5.13.1")>]
[<assembly: AssemblyFileVersionAttribute("5.13.1")>]
[<assembly: AssemblyMetadataAttribute("BuildDate", "2019-04-22")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "FAKE - F# Make Deploy tool"

    [<Literal>]
    let Guid = "413E2050-BECC-4FA6-87AA-5A74ACE9B8E1"

    [<Literal>]
    let AssemblyProduct = "FAKE - F# Make"

    [<Literal>]
    let AssemblyVersion = "5.13.1"

    [<Literal>]
    let AssemblyInformationalVersion = "5.13.1"

    [<Literal>]
    let AssemblyFileVersion = "5.13.1"

    [<Literal>]
    let AssemblyMetadata_BuildDate = "2019-04-22"
