//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.5466
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("EE5621DB-B86B-44eb-987F-9C94BCC98441")]
[assembly: AssemblyTitle("Calculator library")]
[assembly: AssemblyDescription("Sample project for FAKE - F# MAKE")]
[assembly: AssemblyProduct("Calculator library")]
[assembly: AssemblyVersion("0.2")]
[assembly: AssemblyFileVersion("0.2")]
[assembly: AssemblyDelaySign(false)]


