// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MyTitle")>]
[<assembly: AssemblyProductAttribute("MyProduct")>]
[<assembly: AssemblyVersionAttribute("0.0.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("0.0.0.0")>]
do ()

