// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Code coverage with Coverlet")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.18.0")>]
[<assembly: AssemblyInformationalVersionAttribute("5.18.0")>]
[<assembly: AssemblyFileVersionAttribute("5.18.0")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2019-10-21")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Code coverage with Coverlet"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.18.0"
    let [<Literal>] AssemblyInformationalVersion = "5.18.0"
    let [<Literal>] AssemblyFileVersion = "5.18.0"
    let [<Literal>] AssemblyMetadata_BuildDate = "2019-10-21"
