// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Experimental Lib")>]
[<assembly: GuidAttribute("5AA28AED-B9D8-4158-A594-32FE5ABC5713")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("4.60.0")>]
[<assembly: AssemblyInformationalVersionAttribute("4.60.0")>]
[<assembly: AssemblyFileVersionAttribute("4.60.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Experimental Lib"
    let [<Literal>] Guid = "5AA28AED-B9D8-4158-A594-32FE5ABC5713"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "4.60.0"
    let [<Literal>] AssemblyInformationalVersion = "4.60.0"
    let [<Literal>] AssemblyFileVersion = "4.60.0"
