
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
///[omit]
module Fake.AssemblyInfo
#nowarn "49" // uppercase argument names
#nowarn "67" // this type test or downcast will always hold
#nowarn "66" // this upcast is unnecessary - the types are identical
#nowarn "58" // possible incorrect indentation..
#nowarn "57" // do not use create_DelegateEvent
#nowarn "51" // address-of operator can occur in the code
open System
open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices

exception ReturnException183c26a427ae489c8fd92ec21a0c9a59 of obj
exception ReturnNoneException183c26a427ae489c8fd92ec21a0c9a59

[<assembly: ComVisible (false)>]
[<assembly: CLSCompliant (false)>]
[<assembly: Guid ("d6dd5aec-636d-4354-88d6-d66e094dadb5")>]
[<assembly: AssemblyTitle ("FAKE - F# Make Lib")>]
[<assembly: AssemblyProduct ("FAKE - F# Make Lib")>]
[<assembly: AssemblyVersion ("0.2")>]
[<assembly: AssemblyFileVersion ("0.2")>]
[<assembly: AssemblyDelaySign (false)>]
()
