// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Running the ILMerge static linker tool")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.9.4")>]
[<assembly: AssemblyInformationalVersionAttribute("5.9.4-alpha")>]
[<assembly: AssemblyFileVersionAttribute("5.9.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Running the ILMerge static linker tool"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.9.4"
    let [<Literal>] AssemblyInformationalVersion = "5.9.4-alpha"
    let [<Literal>] AssemblyFileVersion = "5.9.4"
