//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.5466
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("A539B42C-CB9F-4a23-8E57-AF4E7CEE5BAA")]
[assembly: AssemblyTitle("Calculator Command line tool")]
[assembly: AssemblyDescription("Sample project for FAKE - F# MAKE")]
[assembly: AssemblyProduct("Calculator Command line tool")]
[assembly: AssemblyVersion("0.2")]
[assembly: AssemblyFileVersion("0.2")]
[assembly: AssemblyDelaySign(false)]


