// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("FAKE - F# Make Deploy Web")]
[assembly: GuidAttribute("27BA7705-3F57-47BE-B607-8A46B27AE876")]
[assembly: AssemblyProductAttribute("FAKE - F# Make")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
