// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Deploy Web")>]
[<assembly: GuidAttribute("27BA7705-3F57-47BE-B607-8A46B27AE876")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("5.0.0")>]
[<assembly: AssemblyFileVersionAttribute("5.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Deploy Web"
    let [<Literal>] Guid = "27BA7705-3F57-47BE-B607-8A46B27AE876"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.0.0"
    let [<Literal>] AssemblyInformationalVersion = "5.0.0"
    let [<Literal>] AssemblyFileVersion = "5.0.0"