// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Deploy Web")>]
[<assembly: GuidAttribute("27BA7705-3F57-47BE-B607-8A46B27AE876")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("4.59.1")>]
[<assembly: AssemblyInformationalVersionAttribute("4.59.1")>]
[<assembly: AssemblyFileVersionAttribute("4.59.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Deploy Web"
    let [<Literal>] Guid = "27BA7705-3F57-47BE-B607-8A46B27AE876"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "4.59.1"
    let [<Literal>] AssemblyInformationalVersion = "4.59.1"
    let [<Literal>] AssemblyFileVersion = "4.59.1"
