//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("27BA7705-3F57-47BE-B607-8A46B27AE876")]
[assembly: AssemblyTitle("FAKE - F# Make Deploy Web")]
[assembly: AssemblyProduct("FAKE - F# Make Deploy Web")]
[assembly: AssemblyVersion("LocalBuild")]
[assembly: AssemblyFileVersion("LocalBuild")]
[assembly: AssemblyDelaySign(false)]


