// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("")>]
[<assembly: AssemblyProductAttribute("")>]
[<assembly: AssemblyVersionAttribute("")>]
[<assembly: AssemblyInformationalVersionAttribute("")>]
[<assembly: AssemblyFileVersionAttribute("")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = ""
    let [<Literal>] AssemblyProduct = ""
    let [<Literal>] AssemblyVersion = ""
    let [<Literal>] AssemblyInformationalVersion = ""
    let [<Literal>] AssemblyFileVersion = ""
