// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Paket Dependency Manager")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.19.2")>]
[<assembly: AssemblyInformationalVersionAttribute("5.19.2-alpha.local.1+2020-03-06-09-23")>]
[<assembly: AssemblyFileVersionAttribute("5.19.2")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2020-03-06")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Paket Dependency Manager"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.19.2"
    let [<Literal>] AssemblyInformationalVersion = "5.19.2-alpha.local.1+2020-03-06-09-23"
    let [<Literal>] AssemblyFileVersion = "5.19.2"
    let [<Literal>] AssemblyMetadata_BuildDate = "2020-03-06"
