// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Running signtool commands")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.16.1")>]
[<assembly: AssemblyInformationalVersionAttribute("5.16.1")>]
[<assembly: AssemblyFileVersionAttribute("5.16.1")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2019-10-11")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Running signtool commands"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.16.1"
    let [<Literal>] AssemblyInformationalVersion = "5.16.1"
    let [<Literal>] AssemblyFileVersion = "5.16.1"
    let [<Literal>] AssemblyMetadata_BuildDate = "2019-10-11"
