// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Sql Server Data Tools DacPac operations")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.19")>]
[<assembly: AssemblyInformationalVersionAttribute("5.19.0-alpha.local.1")>]
[<assembly: AssemblyFileVersionAttribute("5.19.0")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2019-12-16")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Sql Server Data Tools DacPac operations"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.19"
    let [<Literal>] AssemblyInformationalVersion = "5.19.0-alpha.local.1"
    let [<Literal>] AssemblyFileVersion = "5.19.0"
    let [<Literal>] AssemblyMetadata_BuildDate = "2019-12-16"
