//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("78B65159-BCE7-413A-A7A7-3B7BB8277E72")]
[assembly: AssemblyTitle("Fake_Website")]
[assembly: AssemblyDescription("Sample website for FAKE - F# MAKE")]
[assembly: AssemblyProduct("Fake_Website")]
[assembly: AssemblyVersion("0.1")]
[assembly: AssemblyFileVersion("0.1")]
[assembly: AssemblyDelaySign(false)]


