//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("78B65159-BCE7-413A-A7A7-3B7BB8277E72")]
[assembly: AssemblyTitle("Fake_Website")]
[assembly: AssemblyDescription("Sample website for FAKE - F# MAKE")]
[assembly: AssemblyProduct("Fake_Website")]
[assembly: AssemblyVersion("0.2")]
[assembly: AssemblyFileVersion("0.2")]
[assembly: AssemblyDelaySign(false)]


