// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Command line tool")>]
[<assembly: GuidAttribute("fb2b540f-d97a-4660-972f-5eeff8120fba")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.13.1")>]
[<assembly: AssemblyInformationalVersionAttribute("5.13.1")>]
[<assembly: AssemblyFileVersionAttribute("5.13.1")>]
[<assembly: AssemblyMetadataAttribute("BuildDate", "2019-04-22")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "FAKE - F# Make Command line tool"

    [<Literal>]
    let Guid = "fb2b540f-d97a-4660-972f-5eeff8120fba"

    [<Literal>]
    let AssemblyProduct = "FAKE - F# Make"

    [<Literal>]
    let AssemblyVersion = "5.13.1"

    [<Literal>]
    let AssemblyInformationalVersion = "5.13.1"

    [<Literal>]
    let AssemblyFileVersion = "5.13.1"

    [<Literal>]
    let AssemblyMetadata_BuildDate = "2019-04-22"
