// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FAKE - F# Make Integration into Bitbucket buildserver")>]
[<assembly: AssemblyProductAttribute("FAKE - F# Make")>]
[<assembly: AssemblyVersionAttribute("5.20.4")>]
[<assembly: AssemblyInformationalVersionAttribute("5.20.4")>]
[<assembly: AssemblyFileVersionAttribute("5.20.4")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2021-04-05")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FAKE - F# Make Integration into Bitbucket buildserver"
    let [<Literal>] AssemblyProduct = "FAKE - F# Make"
    let [<Literal>] AssemblyVersion = "5.20.4"
    let [<Literal>] AssemblyInformationalVersion = "5.20.4"
    let [<Literal>] AssemblyFileVersion = "5.20.4"
    let [<Literal>] AssemblyMetadata_BuildDate = "5.20.4"
